fix(spans): adhere attribute name to otel semver
microsoft/kiota-http-go pull request #185
Opened 2024-10-12 12:25 UTC by Strazz1337

Updates the http span attributes to match with the updated OTEL specification.

Fixes #182

2024-10-12 12:26 UTC, Strazz1337 commented on compression_handler.go
> +				semconv.HTTPResponseStatusCode(415))
It feels off that the second attribute is the same as the first one. So I set it to `HTTPResponseStatusCode`, as I expect it to equal the status code that is checked a few lines before this.

2024-10-14 11:27 UTC, andrueastman commented on compression_handler.go
> +	semconv "go.opentelemetry.io/otel/semconv/v1.24.0"
```suggestion
	semconv "go.opentelemetry.io/otel/semconv"
```
Should the imports include the version here? Or will they cause issue incase of an update in the go.mod file?

2024-10-14 11:46 UTC, Strazz1337 commented on compression_handler.go
> +	semconv "go.opentelemetry.io/otel/semconv/v1.24.0"
It did not work when I did not assign the version here. So if you manage to get it working that'd be great :)

2024-10-14 12:10 UTC, musale commented on compression_handler.go
> +	semconv "go.opentelemetry.io/otel/semconv/v1.24.0"
@andrueastman you need to reference the version and yes, it will cause runtime errors if you upgrade the otel sdk and don't have the correct version of `semconv` referenced. I hace seen multiple issues and proposals for this but no progress I'm aware of to mitigate having to update all references of `semconv` usage. See https://github.com/open-telemetry/opentelemetry-go/issues/4886

2024-10-14 13:42 UTC, baywet commented on compression_handler.go
> +	semconv "go.opentelemetry.io/otel/semconv/v1.24.0"
In general we've faced similar issues in other languages. This dependency causes a lot of issues since they ship breaking changes without major revs (to keep the version aligned with the other packages roughly). We've resulted NOT to use this package in other languages because of that. Yes it introduces misalignment possibilities/added maintenance burden because of that.
I hope this additional context helps!

2024-12-13 12:42 UTC, baywet commented
@Strazz1337 gentle reminder on this one. Are you still working on it?

2024-12-13 14:24 UTC, Strazz1337 commented
@baywet fixed. 

Somehow git sees the following files as fully changed, while only the setAttributes methods are clearly updated:
- compression_handler.go
- retry_handler.go

2024-12-13 17:10 UTC, baywet requested changes
Thank you for making the changes! A couple additional remarks

2024-12-13 17:10 UTC, baywet commented on span_attributes.go
> +	HttpResponseHeaderContentTypeAttribute = attribute.Key("http.response.header.content_type")
```suggestion
	HttpResponseHeaderContentTypeAttribute = attribute.Key("http.response.header.content-type")
```

2024-12-13 17:10 UTC, baywet commented on span_attributes.go
> +	UrlUriSchemeAttribute = attribute.Key("url.uri_scheme")
```suggestion
	UrlUriTemplateAttribute = attribute.Key("url.uri_template")
```

2024-12-13 17:10 UTC, baywet commented on nethttp_request_adapter.go
> +	span.SetAttributes(UrlUriSchemeAttribute.String(decodedUriTemplate))
```suggestion
	span.SetAttributes(UrlUriTemplateAttribute.String(decodedUriTemplate))
```

2024-12-13 17:10 UTC, baywet commented on CHANGELOG.md
>  - Fixed a bug where headers inspection handler would fail upon receiving an error.
needs to move to a new version
And the version in the user agent handler needs to be bumped

2024-12-13 17:10 UTC, baywet commented on nethttp_request_adapter.go
> +				attribute.String("http.request.header.content-type", request.Header.Get("Content-Type")),
should be moved to the constants to align with the other attributes

2024-12-13 17:13 UTC, baywet commented on CHANGELOG.md
>  - Fixed a bug where headers inspection handler would fail upon receiving an error.
fixed

2024-12-13 17:17 UTC, baywet approved these changes
Thanks for the contribution!

Do you want to take on java next? https://github.com/microsoft/kiota-java/issues/1540

2024-12-13 17:18 UTC, merged